dota2bbq/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns("dota2bbq.views",
    url(r"^$", "index"),
    url(r"^heroes/$", "heroes"),
    url(r"^items/$", "items"),
    url(r"^community/$", "community"),
    url(r"^about/$", "about"),
    url(r"^hero/(?P<hero_name>[\w '-]+)/$", "hero"),
    url(r"^signin/$", "signin"),
    url(r"^signoff/$", "signoff"),
)

eclipse9614/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import settings
admin.autodiscover()



urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('dota2bbq.urls')),
    url(r'^manager/', include('manager.urls')),
    url(r'^feed/', include('feed.urls')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

feed/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns("feed.views",
    url(r"^combined/$", "combined"),
    url(r"^items/$", "items"),
    url(r"^feed$", "feed"),
)

dota2bbq/models.py
from django.db import models
from manager.models import SkillBuildModelField

class Hero(models.Model):
	FACTIONS = (
		('RA', 'Radient'),
		('DI', 'Dire'),
		('NE', 'Netural')
	)

	CLASSES = (
		("STR", 'Strength'),
		("AGI", 'Agility'),
		("INT", 'Intelligence')
	)
	name = models.CharField(max_length = 30)
	faction = models.CharField(max_length = 2, choices = FACTIONS)
	specialty = models.CharField(max_length = 3, choices = CLASSES)
	lore = models.TextField()
	basic_str = models.PositiveSmallIntegerField()
	basic_agi = models.PositiveSmallIntegerField()
	basic_int = models.PositiveSmallIntegerField()
	str_inc = models.FloatField()
	agi_inc = models.FloatField()
	int_inc = models.FloatField()
	movement = models.PositiveSmallIntegerField()
	armor = models.FloatField()
	min_dmg = models.PositiveSmallIntegerField()
	max_dmg = models.PositiveSmallIntegerField()

	def __unicode__(self):
		return self.name


class Item(models.Model):
	TYPES = (
		(1, 'Consumables'),
		(2, "Attributes"),
		(3, "Armaments"),
		(4, 'Arcane'),
		(5, 'Common'),
		(6, 'Support'),
		(7, 'Caster'),
		(8, 'Weapons'),
		(9, 'Armor'),
		(10, 'Artifacts'),
		(11, 'Secret Shop'),
		(0, 'Hidden'),
	)

	name =  models.CharField(max_length = 30)
	description = models.TextField()
	cost = models.SmallIntegerField()
	usage = models.TextField(blank = True)
	attributes = models.TextField(blank = True)
	kind = models.PositiveSmallIntegerField(choices = TYPES)
	recipe = models.ManyToManyField('self', blank = True, symmetrical=False, through='Composition')

	def __unicode__(self):
		return self.name

	@classmethod
	def get_kinds_display(cls):
		return cls.TYPES


class Composition(models.Model):
	whole = models.ForeignKey(Item, related_name = 'as_a_whole')
	component = models.ForeignKey(Item, related_name = 'as_a_part')


class Skill(models.Model):
	hero = models.ForeignKey(Hero)
	number = models.PositiveSmallIntegerField()
	name = models.CharField(max_length = 30)
	description = models.TextField()
	activity = models.BooleanField()
	mana_cost = models.TextField(blank = True, null = True)
	cooldown = models.TextField(blank = True, null = True)
	is_main = models.BooleanField(default = True)

	def __unicode__(self):
		return self.name


	def clean(self):
		from django.core.exceptions import ValidationError
		try:
			self.hero.skill_set.exclude(id = self.id).get(number = self.number)
			raise ValidationError('This skill number is used, please use another one')
		except Skill.DoesNotExist:
			pass






class SkillBuild(models.Model):
	hero = models.ForeignKey(Hero)
	number = models.PositiveSmallIntegerField()
	build = SkillBuildModelField(max_length= 100)

	def clean(self):
		super(SkillBuild, self).clean()
		from django.core.exceptions import ValidationError
		#here, check whether the number attribtue is right or wrong
		try:
			self.hero.skillbuild_set.exclude(id = self.id).get(number = self.number)
			raise ValidationError('This skill build number is used, please use another one')
		except SkillBuild.DoesNotExist:
			pass

		#here, check whether the build attribute is right or wrong
		skills_order = self.build.split(',')
		#make sure there are 25 skills in the build

		if len(skills_order) != 25:
			raise ValidationError('A skill build needs 25 steps.')

		#make sure that in one build, there are ten stats build or not at all(invoker)
		#0 means stat
		stats_count = skills_order.count('0')
		#this is the main skills that are upgradable for each hero
		upgradable_skills = self.hero.skill_set.filter(is_main = True).order_by('number').values_list('id', flat = True)

		skill_counts = [skills_order.count(str(skill)) for skill in upgradable_skills]
		
		if self.hero.name == 'Invoker':
			if stats_count != 0:
				raise ValidationError('Invoker has no stats build')
			if skill_counts != [7, 7, 7, 4]:
				raise ValidationError('Wrong skill distribution for invoker')
		else:
			if stats_count != 10:
				raise ValidationError('A hero should have 10 stats build')
			if skill_counts != [4, 4, 4, 3]:
				raise ValidationError('Wrong skill distribution for this hero')

		#conver the list to comma separated field
		self.build = ','.join(skills_order)

dota2bbq/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.contrib.auth import authenticate, login, logout
from django.forms.models import inlineformset_factory
from dota2bbq.models import Hero, Item, Skill, Composition, SkillBuild



def index(request):
    if 'next' in request.GET and request.user.is_authenticated():
        return redirect(request.GET['next'])
    else:
	   return render(request, 'dota2bbq/index.html')


def heroes(request):
    enqry = {'heroes': Hero.objects.values('name', 'faction', 'specialty')}
    return render(request, 'dota2bbq/heroes.html', enqry)


def items(request):
    items = Item.objects.exclude(kind = 0).order_by('kind', 'cost').values('id', 'name')
    kinds = Item.get_kinds_display()[:-1]
    enqry = [{'kind': kind[1], 'items': items.filter(kind = kind[0])} for kind in kinds]
    return render(request, 'dota2bbq/items.html', {'item_set': enqry})


def community(request):
    return render(request, 'dota2bbq/community.html')


def about(request):
    return render(request, 'dota2bbq/about.html')


def hero(request, hero_name):
    try:
        hero = Hero.objects.get(name = hero_name)
        if hero:
            skills = hero.skill_set.order_by('number')
            skillbuilds = hero.skillbuild_set.order_by('number')
            skillmapper = {skill.id:skill.name for skill in skills}
            skillmapper[0] = u'Stats' #add stats for skill build
            for skillbuild in skillbuilds:
                skillbuild.build = skillbuild.build.split(',')
                skillbuild.build = [skillmapper[int(skill)] for skill in skillbuild.build]

            entry = dict(hero = hero, skills = skills, skillbuilds = skillbuilds)
            return render(request, 'dota2bbq/hero.html', entry)
    except Hero.DoesNotExist:
        raise Http404


def signin(request):
    if request.method == 'POST':
        username = request.POST['username'] if 'username' in request.POST else ''
        password = request.POST['password'] if 'password' in request.POST else ''
        user = authenticate(username = username, password = password)
        if user and user.is_active:
            login(request, user)
        else:
            request.session['login_error'] = 'wrong username or password'
        return redirect(request.META['HTTP_REFERER']) if "HTTP_REFERER" in request.META else redirect('dota2bbq.views.index')
    else:
        return redirect('dota2bbq.views.index')


def signoff(request):
    if request.method == 'POST':
        logout(request)
        return redirect(request.META['HTTP_REFERER'])
    else:
        return redirect('dota2bbq.views.index')

dota2bbq/templates/dota2bbq/about.html
{% extends "dota2bbq/base.html" %}
{% block title %}About{% endblock %}
{% block content %}
<a href="https://github.com/eclipse9614/dota2bbq-django"><img style="position: absolute; top: 62; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>
<div class='hero-unit'>
	<h1>Dota 2 BBQ</h1>
	<p>is a fan site from me. The copyright of all images and data of heroes and items belongs to ValveSoftware and copyright of scripts and apps belongs
		to me. This website is based on Python Django as the back end, Jquery, Jquery UI, Bootstrap as the front end. The open sorce license for this website except the content from Valve is GPL-3.0.
	</p>
	<h5 style='text-align: right;'>Zhoutuo Yang</h5>
</div>
{% endblock %}
{% block scripts %}

{% endblock %}

dota2bbq/templates/dota2bbq/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="/static/favicon.ico">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" >
    <link rel="stylesheet" type="text/css" href="/static/css/jquery-ui-1.10.0.custom.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
</head>
<body>
<header>
    <nav class="navbar navbar-inverse">
        <div class="navbar-inner">
            <a class='brand'>Dota2 BBQ</a>
            <ul class='nav'>
                <li><a href="/">Home</a></li>
                <li class="divider-vertical"></li>
                <li><a href="/heroes">Heroes</a></li>
                <li class="divider-vertical"></li>
                <li><a href="/items">Items</a></li>
                <li class="divider-vertical"></li>
                <li><a href="/community">Community</a></li>
                <li class="divider-vertical"></li>
                <li><a href="/about">About</a></li>
            </ul>
            {% if username %}
            <form class="navbar-form pull-right" id='sign_off' action='/signoff/' method='post'>{% csrf_token %}
                <span class='label'>Username: {{username}}</span>
                <button class="button btn" id='manage_btn' type='button'>Manage</button>
                <button type="submit" class="btn">Sign Off</button>
                {% csrf_token %}
            </form>
            {% else %}
            <form class="navbar-form pull-right" id='sign_in' action='/signin/' method='post'>{% csrf_token %}
                {% if login_error %}
                    <span class='label label-important'>{{login_error}}</span>
                {% endif %}
                <input type="text" placeholder="Username" name='username' required>
                <input type="password" placeholder="Password" name='password' required>
                <button type="submit" class="btn">Sign In</button>
            </form>
            {% endif %}
        </div>
    </nav>
    <div class="modal hide fade" id='result_window'>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Result</h3>
      </div>
      <div class="modal-body">
        <p></p>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
    </div>
</header>

<div id="content">
    {% block content %}{% endblock %}
</div>

<script src="/static/js/jquery-1.9.0.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/jquery-ui-1.10.0.custom.min.js"></script>
<script src="/static/js/base.js"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

dota2bbq/templates/dota2bbq/community.html
{% extends "dota2bbq/base.html" %}
{% block title %}Dota 2 Community{% endblock %}
{% block content %}
	<div class='container'>
		<div class='row'>
			<div class='span4 community_sidebar'>
				<form onsubmit='return addNewFeed()'>
					<legend>Community Sites</legend>
					<div class="input-prepend">
						<span class="add-on">Sites</span>
						<select id='site_picker'>
							<option value='0'>Pick one site</option>
							<option value='http://blog.dota2.com/feed'>Official Dota 2 Blog</option>
							<option value='http://www.joindota.com/feeds/news'>joinDOTA.com</option>
						</select>
					</div>
					<div class='input-prepend'>
						<span class='add-on'>Name</span>
						<input id='newFeedName' type='text' placeholder='Input the new feed name here' required>
					</div>
					<div class='input-prepend'>
						<span class='add-on'>URL</span>
						<input id='newFeedURL' type='text' placeholder='Input the new feed address here' required>
					</div>
					<div class='row'>
						<button class='btn span2 offset1'>Add</button>
					</div>
				</form>
			</div>
			<div class='span8'>
				<div id='feed_display'>
				</div>
			</div>
		</div>

	</div>
{% endblock %}
{% block scripts %}
	<script src="/static/js/community.js"></script>
{% endblock %}

dota2bbq/templates/dota2bbq/hero.html
{% extends "dota2bbq/base.html" %}
{% load extra_filters %}
{% block title%}{{hero.name}}{% endblock %}
{% block content %}
    <div class="container">
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>Reminder!</strong> view details of skills by hovering the icons
        </div>
        <div class="hero_basic row">
            <div class="hero_card span4">
                <table>
                    <tr><td colspan="2" class="hero_name" id="hero_name">{{hero.name}}</td></tr>
                    <tr><td colspan="2"> <img src="/static/images/{{hero.name}}.png" style="width: 256px; height: 144px;"></td></tr>
                    <tr>
                        <td>Faction</td>
                        <td><span class="hero_fac">{{hero.get_faction_display}}</span></td>
                    </tr>
                    <tr>
                        <td>Primary Attribute</td>
                        <td><span class="hero_prim">{{hero.get_specialty_display}}</span></td>
                    </tr>
                </table>
                <table class="stat_table">
                    <tr class="hero_attr">
                        <td><img src="/static/images/33px-Icon_Str.png" width="33" height="33" title="Strength"></td>
                        <td><img src="/static/images/33px-Icon_Agi.png" width="33" height="33" title="Agility"></td>
                        <td><img src="/static/images/33px-Icon_Int.png" width="33" height="33" title="Intelligence"></td>
                    </tr>
                    <tr>
                        <td id="hero_str">{{hero.basic_str}} + {{hero.str_inc}}</td>
                        <td id="hero_agi">{{hero.basic_agi}} + {{hero.agi_inc}}</td>
                        <td id="hero_int">{{hero.basic_int}} + {{hero.int_inc}}</td>
                    </tr>
                    <tr class="hero_attr">
                        <td><img src="/static/images/33px-Icon_Dmg.png" width="46" height="35" title="Damage"></td>
                        <td><img src="/static/images/33px-Icon_Armor.png" width="39" height="37" title="Armor"></td>
                        <td><img src="/static/images/33px-Icon_Mov.png" width="63" height="39" title="Movement"></td>
                    </tr>
                    <tr>
                        <td id="hero_dmg">{{hero.min_dmg}} ~ {{hero.max_dmg}}</td>
                        <td id="hero_armor">{{hero.armor}}</td>
                        <td>{{hero.movement}}</td>
                    </tr>
                </table>
            </div>
            <div class="hero_lore span7 offset1">
                <h2>Lore</h2>
                <p id='hero_lore_para' class='hero_lore_height'>{{hero.lore}}</p>
                <div class='btn btn-inverse' id='hero_lore_btn'>expand</div>
            </div>

        </div>

        <div class="hero_skills">
            <h2>Skills</h2>
            <div id="skill_tabs">
                <ul>
                    {% for skill in skills %}
                        <li><a href='#skill{{skill.number}}'>{{skill.name}}</a></li>
                    {% endfor %}
                </ul>
                {% for skill in skills %}
                    <div id='skill{{skill.number}}' class='skill'
                    data-hero='{{hero.name}}' data-skill='{{skill.name}}' data-index='{{skill.number}}' data-type='{{skill.activity}}'
                    data-manacost='{{skill.mana_cost}}' data-cooldown='{{skill.cooldown}}'>
                        <p>{{skill.description}}</p>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class='hero_skillbuilds'>
            <h2>Skill Builds</h2>
            <div id="skillbuild_tabs">
                <ul>
                    {% for skillbuild in skillbuilds %}
                        <li><a href='#skillbuild{{skillbuild.number}}'>Build {{skillbuild.number}}</a></li>
                    {% endfor %}
                </ul>
                {% for skillbuild in skillbuilds %}
                    <div id='skillbuild{{skillbuild.number}}'>
                        <table class='skill_build_table'>
                            <tr>
                                {% for skill in skillbuild.build %}
                                    {% if skill == 'Stats' %}
                                    <td><img src='/static/images/skills/mini/{{skill|lower}}.png' title data-skill="Stats"></td>
                                    {% else %}
                                    <td><img src='/static/images/skills/mini/{{hero|lower|spaces2underscores|removeapostrophe}}_{{skill|lower|spaces2underscores|removeapostrophe}}.png' title data-skill="{{skill}}"></td>
                                    {% endif %}
                                {% endfor %}
                            </tr>
                        </table>
                        
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>

<div class="modal hide fade" id="hero_full_story">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Full Hero Story</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
     <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="/static/js/hero.js"></script>
{% endblock %}

dota2bbq/templates/dota2bbq/heroes.html
{% extends "dota2bbq/base.html" %}
{% block title %}Heroes{% endblock %}
{% block content %}
{% load extra_filters %}
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Reminder!</strong> Move hero icons around at your will.
</div>
<select id='filter_by_class'>
    <option value='ALL'>Filter By Class</option>
    <option value='STR'>Strength</option>
    <option value='AGI'>Agility</option>
    <option value='INT'>Intelligence</option>
</select>
<select id='filter_by_faction'>
    <option value='ALL'>Filter By Faction</option>
    <option value='RA'>Radient</option>
    <option value='DI'>Dire</option>
</select> 
<input id='filter_by_name' type='text' placeholder='Filter By Name'>
<select id='sort_by_name'>
    <option value='0'>Sort By Name</option>
    <option value='-1'>Ascending</option>
    <option value='1'>Descending</option>
</select> 
<div class='hero_browse'>
        {% for hero in heroes %}
        <div class='hero' data-faction='ALL {{hero.faction}}' data-class='ALL {{hero.specialty}}' data-name='ALL {{hero.name|lower}}'>
            <a href="/hero/{{hero.name}}">
                <img src="/static/images/128px-{{hero.name|lower|spaces2underscores}}.png" width="128px" height="72px">
                <span>{{hero.name}}</span>
            </a>

        </div>
        {% endfor %}
</div>
<div id='dustbin' class='container'>
    <h1>Drop icon here to remove it!</h1>
</div>


{% endblock %}
{% block scripts %}
<script type="text/javascript" src="/static/js/heroes.js"></script>
{% endblock %}

dota2bbq/templates/dota2bbq/index.html
{% extends "dota2bbq/base.html" %}
{% block title %}Dota 2 BBQ{% endblock %}
{% block content %}
    <div id="search">
        <img src="/static/images/dota2logo.png">
        <form id="search_form">
            <input id="search_input" type="text" placeholder="Search for heroes and items here" autofocus>
        </form>
    </div>
{% endblock %}
{% block scripts %}
	<script type="text/javascript" src="/static/js/home.js"></script>
{% endblock %}

dota2bbq/templates/dota2bbq/items.html
{% extends "dota2bbq/base.html" %}
{% block title %}Items{% endblock %}
{% block content %}
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Reminder!</strong> Hover over items to see the details.
</div>
	<div class="items">
		<div class="item_headers">
			{% for items in item_set %}
				<span class="item_header">{{items.kind}}</span>
			{% endfor %}
		</div>
		{% for items in item_set %}
			<div class="items_column">
				{% for item in items.items %}
					<div class="item" id='{{item.id}}'>
						<img src="/static/images/items/{{item.name}}.png" data-id='{{item.id}}' width="85px" height="64px" title>
					</div>
				{% endfor %}
			</div>
		{% endfor %}
	</div>

{% endblock %}

{% block scripts %}
	<script src="/static/js/items.js"></script>
{% endblock %}

dota2bbq/templates/dota2bbq/manage.html
<!DOCTYPE html>
<html>
    <head>
        <title>Dota2 Management</title>
    </head>
    <body>
        <table style='margin: 0 auto;'>
            <tr>
                <th>Heroes</th>
                <th>Items</th>
            </tr>
            <tr>
                <td>
                    <select id='hero_name'>
                        <option value='-1'>Pick a hero to edit or delete</option>
                        {% for hero in heroes %}
                        <option value='{{hero.name}}'>{{hero.name}}</option>
                        {% endfor %}
                    </select>
                    <ul>
                        <li><a id='hero_create' href='/manage/hero_create/'>Create a hero</a></li>
                        <li><a id='hero_edit' href='/manage/hero_edit/'>Edit a hero</a></li>
                        <li><a id='hero_delete' href='/manage/hero_delete/'>Delete a hero</a></li>
                        <li><a id='skill_edit' href='/manage/skill_edit/'>Edit skills of a hero</a></li>
                        <li><a id='skill_build' href='/manage/skill_build/'>Edit skill builds of a hero</a></li>
                    </ul>
                </td>
                <td>
                    <select id='item_name'>
                        <option value='-1'>Pick a item to edit or delete</option>
                        {% for item in items %}
                        <option value='{{item.name}}'>{{item.name}}</option>
                        {% endfor %}
                    </select>
                    <ul>
                        <li><a id='item_create' href='/manage/item_create/'>Create an item</a></li>
                        <li><a id='item_edit' href='/manage/item_edit/'>Edit an item</a></li>
                        <li><a id='item_delete' href='/manage/item_delete/'>Delete an item</a></li>
                    </ul>
                </td>
            </tr>
            <tr>
                <td colspan='2' style='text-align: center;'><button type='button' id='close_btn'><a href='/'>Close</a></button></td>
            </tr>
            
        </table>
        
    <script src='/static/js/jquery-1.8.3.min.js'></script>
    <script src='/static/js/manage.js'></script>
    </body>
</html>

dota2bbq/templates/dota2bbq/skill_build.html
<!DOCTYPE html>
<html>
    <body>
        <form id="input" method="post">
                {% csrf_token %}
                {% for SkillBuildForm in SkillBuildForms %}
                <div style='float: left;'>
                <table>
                {{SkillBuildForm}}
                </table>
                </div>
                {% endfor %}
                {{ SkillBuildForms.management_form }}
            <input type='submit'>
        </form>
    </body>
</html>